echo-webkom/echo-web-backend

- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Bedpres.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- test_scripts/submit_bedpres
Now you can't sign up for a bedpres before it is available.
> ✨ Added time restriction on bedpres registration

- build.gradle.kts
- docker-compose.test.yaml
- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Bedpres.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/test/kotlin/no/uib/echo/BedpresTest.kt
- src/test/kotlin/no/uib/echo/RegistrationTest.kt
When signing up for a bedpres, you will automatically be put on the waitlist if the number of people signed up exceeds bedpres spots.
> ✨ Add auto-close and waitlist for bedpres

- src/main/kotlin/no/uib/echo/plugins/Routing.kt
/status returns 200 OK if backend server is up.
> ✨ Add status route

- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Bedpres.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/test/kotlin/no/uib/echo/BedpresTest.kt
- src/test/kotlin/no/uib/echo/RegistrationTest.kt
- test_scripts/delete_bedpres
- test_scripts/delete_registration
- test_scripts/get_registrations
- test_scripts/submit_bedpres
> ✨ Restrict registration to degree year range

- build.gradle.kts
- gradle.properties
- src/main/kotlin/no/uib/echo/Database.kt
- src/main/kotlin/no/uib/echo/schema/Answer.kt
- src/main/kotlin/no/uib/echo/schema/Bedpres.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/main/resources/db/migration/V2__Change_types.sql
Also add migration for changing VARCHAR -> TEXT data type.
> 🗃 Add Flyway database migration

- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
- src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
Also refactor response message handling.
> ✨ Add spot on waitlist in response

- src/main/kotlin/no/uib/echo/Database.kt
Might improve performance, let's find out :)
> ⚡️ Increase max connections in DB pool

- .env.example
- .github/workflows/cypress_test_dev.yaml
- .github/workflows/cypress_test_prod.yaml
- .gitignore
- docker-compose.ci.yaml
- docker-compose.cypress.yaml
- docker-compose.kotest.yaml
- docker-compose.yaml
- scripts/delete_happening
- scripts/delete_registration
- scripts/get_count_registrations
- scripts/get_registrations
- scripts/submit_happening
- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/test/kotlin/no/uib/echo/BedpresRegistrationTest.kt
- src/test/kotlin/no/uib/echo/BedpresTest.kt
- src/test/kotlin/no/uib/echo/EventRegistrationTest.kt
- src/test/kotlin/no/uib/echo/EventTest.kt
ADMIN_KEY is the new environment variable for access to registrations and events. Also add example .env file.
> ♻️ Combine BEDKOM_KEY and WEBKOM_KEY to single env

- src/main/kotlin/no/uib/echo/schema/Happening.kt
Min and max degree year updated to spots, and tried to compare slug with
type.
> 🚑️ Fix wrong query for Happening

- .github/release.yml
- renovate.json
> Release logs template and Renovate config

- .github/release.yml
- .github/workflows/release_tag.yaml
> 💬 Fix format of release notes

- build.gradle.kts
- docker-compose.ci.yaml
- docker-compose.cypress.yaml
- docker-compose.yaml
- gradle.properties
- renovate.json
- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
> ✨ Add auto-email send for registrations

- build.gradle.kts
- scripts/submit_happening
- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Answer.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/main/resources/db/migration/V7__Contact_email.sql
- src/main/resources/templates/registrations_link.ftl
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Nå får de som arrangerer en mail med en (hemmelig) link som gir dem liste over alle påmeldte.
> ✨ Add automated registration lists for happenings

- src/main/kotlin/no/uib/echo/schema/Happening.kt
Så man ikke blir spammet ned med mails om man bare endrer litt på f.eks. teksten til arrangementet.
> 🩹 Only send email on happening creation, not update

- docker-compose.yaml
- scripts/submit_happening
- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Så vi kan skru av og på om det skal sendes mail med påmelding eller opprettelse av arrangementer.
> 🏗 Add feature toggle for email sending

- .github/workflows/rebase.yaml
Samme som https://github.com/echo-webkom/echo-web-frontend/pull/705.
> 🚀 Add action for auto-rebasing pull requests

- src/main/kotlin/no/uib/echo/schema/Answer.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Mail er ikke case-sensitive, så vår sjekk burde heller ikke være det.
> 🐛 Make email in registration case insensitive

- .env.example
> 📝 Update .env.example

- src/main/resources/db/migration/V8__Default_values.sql
Migration fra https://github.com/echo-webkom/echo-web-backend/pull/195 var ikke helt riktig, denne skal funke.
> 🐛 Fix broken migration

- scripts/submit_happening
- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/resources/db/migration/V9__Happening_title.sql
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Slik at bekreftelsesmailene har tittel og ikke slug.
> ✨ Add title field to Happening

- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Spots < 1 gir uendelig plasser.
Hører sammen med https://github.com/echo-webkom/echo-web-frontend/pull/751.
> ✨ Spot ranges with infinite spots

- src/main/kotlin/no/uib/echo/Database.kt
Vi har hatt noen problemer med at vi bruker for mye minne, kan hende dette hjelper litt.
> 🔧 Reduce max pool size

- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
Nå får man opp om man har plass eller hvilken ventelisteplass man har om man prøve å melde seg på flere ganger.
> ✨ Better responses for registration

- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
Fikser feil ventelisteplass i https://github.com/echo-webkom/echo-web-backend/pull/210.
Må sjekke dato på tidligere påmeldinger for å få riktig plass på venteliste (om du melder deg på mer enn én gang).
Det gidder jeg ikke finne ut av, så fjerner hvilken plass du har på venteliste på respons.
> 🐛 Remove wrong waitListSpot in response

- src/main/kotlin/no/uib/echo/Database.kt
Så vi kan tweake uten å endre koden hver gang.
> 🎨 Add environment variable for max pool size

- src/main/kotlin/no/uib/echo/Database.kt
- src/main/kotlin/no/uib/echo/schema/Answer.kt
- src/main/resources/db/migration/V10__Answer_not_null.sql
Exposed støtter nå composite foreign keys, har implementert ordentlig.
> ♻️ Remove workaround for Answer FK's

- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/DatabaseHandler.kt
- src/main/resources/application.conf
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Er sånn man egentlig skal gjøre det.
https://ktor.io/docs/configurations.html#environment-variables
> 🎨 Use ktor config for environment variables

- src/main/kotlin/no/uib/echo/Email.kt
Byttet til syntaks som lager og lukker en ny client for hver request.
> 🐛 Fix bug where client closes after first request

- .github/workflows/release_tag.yaml
GitHub CLI har endelig lagt det til.
> 🚀 Auto-generate release notes on new release

- src/main/kotlin/no/uib/echo/schema/Happening.kt
Burde fikse broken PwC bedpres.
> 🐛 Fix spot range not inserted in database

- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Om man sletter en påmelding, vil neste person på venteliste automatisk rykke opp.
> ✨ Add ability to delete registrations

- docker-compose.cypress.yaml
- docker-compose.kotest.yaml
- docker-compose.yaml
> ⬆️ Bump Postgres version to match Heroku

- scripts/submit_happening
- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/resources/db/migration/V11__Happening_date.sql
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Slik at det ikke går ann å melde seg på etter at arrangementet har vært.
> 🩹 Add happening date to restrict registration

- src/main/kotlin/no/uib/echo/plugins/Routing.kt
Slik at man alltid havner på venteliste dersom det er noen andre på venteliste.
> 🐛 Use registrations on waitlist to determine waitlist spot

- src/main/kotlin/no/uib/echo/plugins/Routing.kt
> 🚑 Update registration only where slug is correct

- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
Bare sletter alle (per slug) og setter inn nye om de skal endres på.
> ♻️ Improve spotrange update logic

- src/main/kotlin/no/uib/echo/Application.kt
- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/main/resources/application.conf
- src/main/resources/db/migration/V13_Reg_verify_token.sql
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Høres sammen med https://github.com/echo-webkom/echo-web-frontend/pull/969.
> 🔒️ Make form registration the only way

- .env.example
- .github/workflows/cypress_test.yaml
- build.gradle.kts
- docker-compose.cypress.yaml
- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/Response.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/Answer.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
- src/main/kotlin/no/uib/echo/schema/Registration.kt
- src/main/kotlin/no/uib/echo/schema/SpotRange.kt
- src/test/kotlin/no/uib/echo/HappeningRegistrationTest.kt
- src/test/kotlin/no/uib/echo/HappeningTest.kt
Gir bedre typesikkerhet pga. det er et native Kotlin bibliotek.
> 🎨 Switch to kotlinx.serialization from Gson

- src/main/kotlin/no/uib/echo/DatabaseHandler.kt
- src/main/kotlin/no/uib/echo/plugins/Routing.kt
- src/main/kotlin/no/uib/echo/schema/User.kt
- src/main/resources/db/migration/V14__User.sql
lagt till et endpoint /user som returnerer dummy data
> ✨ /user endpoint

- src/main/kotlin/no/uib/echo/Email.kt
- src/main/kotlin/no/uib/echo/schema/Happening.kt
Fikser at arrangør får feil link.
> 🐛 Fix incorrect reference
